services:
  db:
    image: postgres:16-alpine
    container_name: siap_db_compose
    restart: unless-stopped
    environment:
      POSTGRES_USER: siapuser
      POSTGRES_PASSWORD: thegrandinquisitor# # Replace with a strong password
      POSTGRES_DB: siapdb
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./backend/db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init.sql
    # Remove port mapping if not needed for direct external access after setup
    # ports:
    #   - "6543:5432" 
    networks:
      - siap_network_compose

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siap_backend_compose
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_USER: siapuser
      DB_PASSWORD: thegrandinquisitor# # Must match POSTGRES_PASSWORD above
      DB_HOST: db # Service name 'db' from this docker-compose file
      DB_PORT: 5432
      DB_NAME: siapdb
      JWT_SECRET: 3704a086ffefb5d6e7a6f4e144742d157e3bebeb5b9053328258936ac495f52b # Replace with a strong JWT secret
      JWT_EXPIRES_IN: 1d
    ports:
      - "5000:5000" # Expose backend port
    volumes:
      - ./backend/uploads:/app/uploads # Persist uploads
    networks:
      - siap_network_compose

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Removed args for REACT_APP_API_BASE_URL to use default for local development
    container_name: siap_frontend_compose
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_BASE_URL: https://sisteminformasiadministrasipengarsipan-siap.com/api
    ports:
      - "80:80" # Redirect HTTP to HTTPS
      - "443:443" # Expose frontend Nginx HTTPS port
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Ensure updated nginx.conf is used
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount the entire letsencrypt directory
      - ./backend/uploads:/app/backend/uploads:ro # Mount uploads directory from backend for Nginx to serve
    networks:
      - siap_network_compose

volumes:
  db-data:

networks:
  siap_network_compose: # Use a different network name
    driver: bridge
